[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"

[project]
name = "piaps"
version = "0.1.0"
description = "Backend for PiAPS Coursework"
readme = "README.md"
requires-python = "~=3.12"

authors = [
    { name = "Factorino", email = "masenkin73@gmail.com" }
]
maintainers = [
    { name = "Factorino", email = "masenkin73@gmail.com" }
]

classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]

dependencies = [
    "adaptix>=3.0.0b11",
    "alembic>=1.18.4",
    "bcrypt>=5.0.0",
    "dishka>=1.8.0",
    "fastapi[python-multipart]>=0.135.1",
    "pyjwt[crypto]>=2.11.0",
    "sqlalchemy[aiosqlite]>=2.0.48",
    "uvicorn>=0.41.0",
]

[project.scripts]
piaps = "piaps.main.api:main"

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "ipython>=9.8.0",
    "pre-commit>=4.5.0",
]
lint = [
    "mypy>=1.19.0",
    "ruff>=0.14.8",
]
