"""Init migration

Revision ID: cc71f66b7523
Revises: 
Create Date: 2026-03-13 15:56:41.171964

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc71f66b7523"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("departments",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("code", sa.String(length=20), nullable=False),
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_departments"))
    )
    op.create_index(op.f("ix_departments_code"), "departments", ["code"], unique=True)
    op.create_index(op.f("ix_departments_name"), "departments", ["name"], unique=True)
    op.create_table("payroll_items",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("code", sa.String(length=20), nullable=False),
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column("payroll_type", sa.Enum("ACCRUAL", "DEDUCTION", name="payrollitemtype"), nullable=False),
    sa.Column("calc_type", sa.Enum("FIXED", "PERCENT", name="payrollcalculationtype"), nullable=False),
    sa.Column("value", sa.Numeric(precision=15, scale=2), nullable=True),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_payroll_items"))
    )
    op.create_index(op.f("ix_payroll_items_calc_type"), "payroll_items", ["calc_type"], unique=False)
    op.create_index(op.f("ix_payroll_items_code"), "payroll_items", ["code"], unique=True)
    op.create_index(op.f("ix_payroll_items_name"), "payroll_items", ["name"], unique=True)
    op.create_index(op.f("ix_payroll_items_payroll_type"), "payroll_items", ["payroll_type"], unique=False)
    op.create_table("positions",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("code", sa.String(length=20), nullable=False),
    sa.Column("name", sa.String(length=100), nullable=False),
    sa.Column("base_salary", sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_positions"))
    )
    op.create_index(op.f("ix_positions_code"), "positions", ["code"], unique=True)
    op.create_index(op.f("ix_positions_name"), "positions", ["name"], unique=True)
    op.create_table("employees",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("code", sa.String(length=20), nullable=False),
    sa.Column("full_name", sa.String(length=300), nullable=False),
    sa.Column("hire_date", sa.Date(), nullable=False),
    sa.Column("department_id", sa.UUID(), nullable=False),
    sa.Column("position_id", sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(["department_id"], ["departments.id"], name=op.f("fk_employees_department_id_departments")),
    sa.ForeignKeyConstraint(["position_id"], ["positions.id"], name=op.f("fk_employees_position_id_positions")),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_employees"))
    )
    op.create_index(op.f("ix_employees_code"), "employees", ["code"], unique=True)
    op.create_index(op.f("ix_employees_department_id"), "employees", ["department_id"], unique=False)
    op.create_index(op.f("ix_employees_position_id"), "employees", ["position_id"], unique=False)
    op.create_table("payroll_sheets",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("employee_id", sa.UUID(), nullable=False),
    sa.Column("period", sa.Date(), nullable=False),
    sa.Column("status", sa.Enum("DRAFT", "CONFIRMED", "CANCELLED", name="payrollstatus"), nullable=False),
    sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], name=op.f("fk_payroll_sheets_employee_id_employees")),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_payroll_sheets"))
    )
    op.create_index(op.f("ix_payroll_sheets_employee_id"), "payroll_sheets", ["employee_id"], unique=False)
    op.create_index(op.f("ix_payroll_sheets_period"), "payroll_sheets", ["period"], unique=False)
    op.create_table("users",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("username", sa.String(length=30), nullable=False),
    sa.Column("password_hash", sa.LargeBinary(), nullable=False),
    sa.Column("role", sa.Enum("EMPLOYEE", "ACCOUNTANT", "ADMINISTRATOR", name="userrole"), nullable=False),
    sa.Column("employee_id", sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], name=op.f("fk_users_employee_id_employees")),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_users"))
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table("payroll_records",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("employee_id", sa.UUID(), nullable=False),
    sa.Column("payroll_item_id", sa.UUID(), nullable=False),
    sa.Column("period", sa.Date(), nullable=False),
    sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column("comment", sa.Text(), nullable=True),
    sa.Column("payroll_sheet_id", sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], name=op.f("fk_payroll_records_employee_id_employees")),
    sa.ForeignKeyConstraint(["payroll_item_id"], ["payroll_items.id"], name=op.f("fk_payroll_records_payroll_item_id_payroll_items")),
    sa.ForeignKeyConstraint(["payroll_sheet_id"], ["payroll_sheets.id"], name=op.f("fk_payroll_records_payroll_sheet_id_payroll_sheets")),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_payroll_records"))
    )
    op.create_index(op.f("ix_payroll_records_employee_id"), "payroll_records", ["employee_id"], unique=False)
    op.create_index(op.f("ix_payroll_records_payroll_item_id"), "payroll_records", ["payroll_item_id"], unique=False)
    op.create_index(op.f("ix_payroll_records_payroll_sheet_id"), "payroll_records", ["payroll_sheet_id"], unique=False)
    op.create_index(op.f("ix_payroll_records_period"), "payroll_records", ["period"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payroll_records_period"), table_name="payroll_records")
    op.drop_index(op.f("ix_payroll_records_payroll_sheet_id"), table_name="payroll_records")
    op.drop_index(op.f("ix_payroll_records_payroll_item_id"), table_name="payroll_records")
    op.drop_index(op.f("ix_payroll_records_employee_id"), table_name="payroll_records")
    op.drop_table("payroll_records")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_payroll_sheets_period"), table_name="payroll_sheets")
    op.drop_index(op.f("ix_payroll_sheets_employee_id"), table_name="payroll_sheets")
    op.drop_table("payroll_sheets")
    op.drop_index(op.f("ix_employees_position_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_department_id"), table_name="employees")
    op.drop_index(op.f("ix_employees_code"), table_name="employees")
    op.drop_table("employees")
    op.drop_index(op.f("ix_positions_name"), table_name="positions")
    op.drop_index(op.f("ix_positions_code"), table_name="positions")
    op.drop_table("positions")
    op.drop_index(op.f("ix_payroll_items_payroll_type"), table_name="payroll_items")
    op.drop_index(op.f("ix_payroll_items_name"), table_name="payroll_items")
    op.drop_index(op.f("ix_payroll_items_code"), table_name="payroll_items")
    op.drop_index(op.f("ix_payroll_items_calc_type"), table_name="payroll_items")
    op.drop_table("payroll_items")
    op.drop_index(op.f("ix_departments_name"), table_name="departments")
    op.drop_index(op.f("ix_departments_code"), table_name="departments")
    op.drop_table("departments")
    # ### end Alembic commands ###
